version: '3.7'
services:
  application:
    container_name: accent
    network_mode: "host"
    build: .
    depends_on:
      - postgresql
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres@postgresql:5432/accent
  postgresql:
    image: postgres:15.6
    container_name: accent-postgres
    environment:
      - POSTGRES_DB=accent
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - accent_psql:/var/lib/postgresql/data
volumes:
  accent_psql:
